export const SHOP_NAME_AVAILABLE_REQUEST = 'SHOP_NAME_AVAILABLE_REQUEST'
export const SHOP_NAME_AVAILABLE_SUCCESS = 'SHOP_NAME_AVAILABLE_SUCCESS'
export const SHOP_NAME_AVAILABLE_FAIL = 'SHOP_NAME_AVAILABLE_FAIL'

export const CREATE_SHOP_REQUEST = 'CREATE_SHOP_REQUEST'
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS'
export const CREATE_SHOP_FAIL = 'CREATE_SHOP_FAIL'

export const SHOP_DETAILS_REQUEST = 'SHOP_DETAILS_REQUEST'
export const SHOP_DETAILS_SUCCESS = 'SHOP_DETAILS_SUCCESS'
export const SHOP_DETAILS_FAIL = 'SHOP_DETAILS_FAIL'
